### ISSUE TITLE
Please leave it compatible with ConfuserEx

### ISSUE THREAD

**Issue by MrakDev** [HoLLy-HaCKeR/Confuser.Protections.HoLLy#8]
I'm having trouble injecting your protections into Confuser.
I wonder if it's possible, you do something compatible, or help me.
Thank you

**Comment by holly-hacker** [comment]
If you can tell me the actual problem, sure.

**Comment by MrakDev** [comment]
The source code not is compatible, ex: you use public override string Name => "Memory Protection analysis"; === NO COMPATIBLE

corret:
 public override string Name = "Memory Protection analysis";

several others too.
if at all I can not compile their protections together with the KI ConfuserEx

**Comment by holly-hacker** [comment]
You should update your Visual Studio to 2017, these are C# 7 features.

For more information on expression bodies, see here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members

**Comment by MrakDev** [comment]
Serius I love you m8 thank you.
I'll test and tell you the results.

**Comment by MrakDev** [comment]
Okay, now c# is talking "is inaccessible due to its protection level"
![image](https://user-images.githubusercontent.com/20323631/33830421-3e973554-de5b-11e7-9813-69421636f58e.png)

**Comment by holly-hacker** [comment]
That is strange, because I set an assembly attribute to show the internals of the Runtime assembly to the main assembly. Make sure that [this line](https://github.com/HoLLy-HaCKeR/Confuser.Protections.HoLLy/blob/master/Confuser.Protections.HoLLy.Runtime/Properties/AssemblyInfo.cs#L39) is present in your copy of the source.

Proof that it does work for me: ![pic](https://i.imgur.com/Yk6C9Sv.png)

You can always download the latest source from [AppVeyor](https://ci.appveyor.com/project/HoLLy-HaCKeR/confuser-protections-holly/build/artifacts), and decompile it with dnSpy if you need to edit something.

**Comment by MrakDev** [comment]
i already hnow, 
i change type of ObfuscatedValue
![image](https://user-images.githubusercontent.com/20323631/33832299-bcf3703c-de62-11e7-9595-5dea46286fad.png)
For
![image](https://user-images.githubusercontent.com/20323631/33832308-c6dc8e3a-de62-11e7-85a6-214519f2b3fb.png)
now gave to compile, but when I go to obfs the .exe gives an error.

**Comment by MrakDev** [comment]
I do not really know what to do, I've tried everything, use the appVeyor dll to compile the dll and use it in confuser, try to get the src of the dll in dnspy, solve the problems by VS
:(

**Comment by holly-hacker** [comment]
`ObfuscatedValue` is meant to be internal, making it public is just a workaround but if it works for you I guess that's fine.

So what exactly is the issue now? Not being able to run a module protected with this? Keep in mind that this is still a work-in-progress, and please be specific with what the issue is.

**Comment by MrakDev** [comment]
Could you compile the entire project? in appVeyor?, type with all confuser config
https://github.com/yck1509/ConfuserEx

**Comment by MrakDev** [comment]
the only thing I need is memory protection
:/

**Comment by holly-hacker** [comment]
If all you need is memory protection, annotate a property with the following attribute:

`[Obfuscation(Exclude = false, Feature = "memory protection")]`

Note that this only works on primitive types such as int (and family), float + double, string and enum.

**Comment by MrakDev** [comment]
I did not understand (sorry for being annoying)

**Comment by holly-hacker** [comment]
Before protection, it will look like this:

		private static int _normal = 100;

		[Obfuscation(Exclude = false, Feature = "memory protection")]
		private static int _special = 100;

And after protection, it will look like this:

		private static int _normal = 100;

		private static \u206E\u200E\u200E(...)\u206A\u202E<int> _special = 100;

**Comment by MrakDev** [comment]
Do you have any social networks? ex skype
you know I need something to protect the string inside the memory. to prevent from memory editor like cheat engine

**Comment by holly-hacker** [comment]
I just explained it to you. If it still isn't clear, perhaps you should use more mature software than this, which may have more clear (or any) documentation.
